In [6]:
# Data Cleaning

# This notebook prepares the PSID 2017 and 2019 data for analysis by loading the extracted dataset, renaming variables, handling missing values, creating donation measures, and exporting a cleaned dataset.

In [1]:
## Load Data
import pandas as pd

In [2]:
df = pd.read_excel("../data/J364915_clean.xlsx")

In [3]:
## Initial Data Check
df.head()

,ER66001,ER66002,ER66017,ER66018,ER66025,ER66164,ER68420,ER71040,ER71042,ER71044,...,ER77074,ER77076,ER77078,ER77080,ER77082,ER77085,ER77448,ER77511,ER77599,ER77601
0,3.0,5620.0,59.0,2.0,2.0,5.0,4.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,11028.0,1200.0,11.0,4.0
1,3.0,8559.0,57.0,2.0,2.0,1.0,2.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,60970.0,195000.0,12.0,4.0
2,3.0,6510.0,43.0,2.0,3.0,5.0,4.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,9380.0,0.0,12.0,5.0
3,3.0,9172.0,42.0,1.0,3.0,1.0,1.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,10000.0,2000.0,10.0,2.0
4,3.0,7682.0,27.0,2.0,3.0,1.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,31000.0,14000.0,12.0,4.0

In [4]:
df.shape

(10822, 46)

In [9]:
df.columns.tolist()

['ER66001',
 'ER66002',
 'ER66017',
 'ER66018',
 'ER66025',
 'ER66164',
 'ER68420',
 'ER71040',
 'ER71042',
 'ER71044',
 'ER71046',
 'ER71048',
 'ER71050',
 'ER71052',
 'ER71054',
 'ER71056',
 'ER71058',
 'ER71060',
 'ER71063',
 'ER71426',
 'ER71485',
 'ER71538',
 'ER71540',
 'ER72001',
 'ER72002',
 'ER72017',
 'ER72018',
 'ER72025',
 'ER72164',
 'ER74428',
 'ER77062',
 'ER77064',
 'ER77066',
 'ER77068',
 'ER77070',
 'ER77072',
 'ER77074',
 'ER77076',
 'ER77078',
 'ER77080',
 'ER77082',
 'ER77085',
 'ER77448',
 'ER77511',
 'ER77599',
 'ER77601']

In [6]:
rename_map = {
    # 2017
    "ER66001": "release_2017",
    "ER66002": "family_id_2017",
    "ER66017": "age_2017",
    "ER66018": "sex_2017",
    "ER66025": "life_satisfaction_2017",
    "ER66164": "employment_status_2017",
    "ER68420": "health_status_2017",
    "ER71040": "donor_status_2017",
    "ER71042": "religious_donations_2017",
    "ER71044": "combo_donations_2017",
    "ER71046": "needy_donations_2017",
    "ER71048": "health_donations_2017",
    "ER71050": "education_donations_2017",
    "ER71052": "youth_donations_2017",
    "ER71054": "cultural_donations_2017",
    "ER71056": "community_donations_2017",
    "ER71058": "environment_donations_2017",
    "ER71060": "international_peace_donations_2017",
    "ER71063": "other_donations_2017",
    "ER71426": "family_income_2017",
    "ER71485": "wealth_2017",
    "ER71538": "education_2017",
    "ER71540": "marital_status_2017",

    # 2019
    "ER72001": "release_2019",
    "ER72002": "family_id_2019",
    "ER72017": "age_2019",
    "ER72018": "sex_2019",
    "ER72025": "life_satisfaction_2019",
    "ER72164": "employment_status_2019",
    "ER74428": "health_status_2019",
    "ER77062": "donor_status_2019",
    "ER77064": "religious_donations_2019",
    "ER77066": "combo_donations_2019",
    "ER77068": "needy_donations_2019",
    "ER77070": "health_donations_2019",
    "ER77072": "education_donations_2019",
    "ER77074": "youth_donations_2019",
    "ER77076": "cultural_donations_2019",
    "ER77078": "community_donations_2019",
    "ER77080": "environment_donations_2019",
    "ER77082": "international_peace_donations_2019",
    "ER77085": "other_donations_2019",
    "ER77448": "family_income_2019",
    "ER77511": "wealth_2019",
    "ER77599": "education_2019",
    "ER77601": "marital_status_2019"
}

df = df.rename(columns=rename_map)

In [7]:
df.columns.tolist()

['release_2017',
 'family_id_2017',
 'age_2017',
 'sex_2017',
 'life_satisfaction_2017',
 'employment_status_2017',
 'health_status_2017',
 'donor_status_2017',
 'religious_donations_2017',
 'combo_donations_2017',
 'needy_donations_2017',
 'health_donations_2017',
 'education_donations_2017',
 'youth_donations_2017',
 'cultural_donations_2017',
 'community_donations_2017',
 'environment_donations_2017',
 'international_peace_donations_2017',
 'other_donations_2017',
 'family_income_2017',
 'wealth_2017',
 'education_2017',
 'marital_status_2017',
 'release_2019',
 'family_id_2019',
 'age_2019',
 'sex_2019',
 'life_satisfaction_2019',
 'employment_status_2019',
 'health_status_2019',
 'donor_status_2019',
 'religious_donations_2019',
 'combo_donations_2019',
 'needy_donations_2019',
 'health_donations_2019',
 'education_donations_2019',
 'youth_donations_2019',
 'cultural_donations_2019',
 'community_donations_2019',
 'environment_donations_2019',
 'international_peace_donations_2019',
 'other_donations_2019',
 'family_income_2019',
 'wealth_2019',
 'education_2019',
 'marital_status_2019']

In [8]:
check_cols = [
    "life_satisfaction_2017",
    "life_satisfaction_2019",
    "health_status_2017",
    "health_status_2019",
    "donor_status_2017",
    "donor_status_2019",
    "sex_2017",
    "sex_2019",
    "employment_status_2017",
    "employment_status_2019",
    "marital_status_2017",
    "marital_status_2019"
]

for col in check_cols:
    print("\n", col)
    print(df[col].value_counts(dropna=False).sort_index())

 life_satisfaction_2017
life_satisfaction_2017
0.0     122
1.0    2029
2.0    4150
3.0    2847
4.0     325
5.0     100
8.0      24
9.0      10
NaN    1215
Name: count, dtype: int64

 life_satisfaction_2019
life_satisfaction_2019
0.0      95
1.0    2046
2.0    4242
3.0    2735
4.0     300
5.0     110
8.0      29
9.0      12
NaN    1253
Name: count, dtype: int64

 health_status_2017
health_status_2017
1.0    1477
2.0    3252
3.0    3056
4.0    1381
5.0     414
8.0       5
9.0      22
NaN    1215
Name: count, dtype: int64

 health_status_2019
health_status_2019
1.0    1414
2.0    3170
3.0    3087
4.0    1472
5.0     398
8.0       5
9.0      23
NaN    1253
Name: count, dtype: int64

 donor_status_2017
donor_status_2017
0.0     122
1.0    4255
5.0    5181
8.0      10
9.0      39
NaN    1215
Name: count, dtype: int64

 donor_status_2019
donor_status_2019
0.0      95
1.0    4054
5.0    5385
8.0       5
9.0      30
NaN    1253
Name: count, dtype: int64

 sex_2017
sex_2017
1.0    6549
2.0    3058
NaN    1215
Name: count, dtype: int64

 sex_2019
sex_2019
1.0    6469
2.0    3100
NaN    1253
Name: count, dtype: int64

 employment_status_2017
employment_status_2017
1.0     6672
2.0       39
3.0      619
4.0     1407
5.0      464
6.0      284
7.0      117
99.0       5
NaN     1215
Name: count, dtype: int64

 employment_status_2019
employment_status_2019
1.0     6692
2.0       33
3.0      530
4.0     1489
5.0      448
6.0      258
7.0      112
99.0       7
NaN     1253
Name: count, dtype: int64

 marital_status_2017
marital_status_2017
1.0    4977
2.0    2467
3.0     481
4.0    1252
5.0     429
9.0       1
NaN    1215
Name: count, dtype: int64

 marital_status_2019
marital_status_2019
1.0    4863
2.0    2530
3.0     473
4.0    1296
5.0     406
9.0       1
NaN    1253
Name: count, dtype: int64

In [9]:
import numpy as np

# Replace PSID special missing-value codes with NaN

for col in ["age_2017", "age_2019"]:
    df[col] = df[col].replace(999, np.nan)

for col in ["life_satisfaction_2017", "life_satisfaction_2019"]:
    df[col] = df[col].replace([0, 8, 9], np.nan)

for col in ["health_status_2017", "health_status_2019"]:
    df[col] = df[col].replace([8, 9], np.nan)

for col in ["employment_status_2017", "employment_status_2019"]:
    df[col] = df[col].replace(99, np.nan)

for col in ["education_2017", "education_2019"]:
    df[col] = df[col].replace(99, np.nan)

for col in ["marital_status_2017", "marital_status_2019"]:
    df[col] = df[col].replace(9, np.nan)

In [10]:
df["donor_2017"] = df["donor_status_2017"].map({
    1: 1,
    5: 0
})

df["donor_2019"] = df["donor_status_2019"].map({
    1: 1,
    5: 0
})

In [11]:
donation_cols_2017 = [
    "religious_donations_2017",
    "combo_donations_2017",
    "needy_donations_2017",
    "health_donations_2017",
    "education_donations_2017",
    "youth_donations_2017",
    "cultural_donations_2017",
    "community_donations_2017",
    "environment_donations_2017",
    "international_peace_donations_2017",
    "other_donations_2017"
]

donation_cols_2019 = [
    "religious_donations_2019",
    "combo_donations_2019",
    "needy_donations_2019",
    "health_donations_2019",
    "education_donations_2019",
    "youth_donations_2019",
    "cultural_donations_2019",
    "community_donations_2019",
    "environment_donations_2019",
    "international_peace_donations_2019",
    "other_donations_2019"
]

special_donation_codes = [99998, 99999, 999998, 999999]

df[donation_cols_2017] = df[donation_cols_2017].replace(
    special_donation_codes, np.nan
)

df[donation_cols_2019] = df[donation_cols_2019].replace(
    special_donation_codes, np.nan
)

In [12]:
df["total_donations_2017"] = df[donation_cols_2017].sum(axis=1, min_count=1)

df["total_donations_2019"] = df[donation_cols_2019].sum(axis=1, min_count=1)

In [13]:
df[
    [
        "donor_2017",
        "total_donations_2017",
        "donor_2019",
        "total_donations_2019"
    ]
].head(10)

   donor_2017  total_donations_2017  donor_2019  total_donations_2019
0         0.0                   0.0         1.0                 300.0
1         0.0                   0.0         0.0                   0.0
2         0.0                   0.0         0.0                   0.0
3         0.0                   0.0         0.0                   0.0
4         0.0                   0.0         0.0                   0.0
5         0.0                   0.0         0.0                   0.0
6         0.0                   0.0         NaN                   NaN
7         0.0                   0.0         0.0                   0.0
8         1.0                 100.0         1.0                 250.0
9         NaN                   NaN         0.0                   0.0

In [14]:
for year in [2017, 2019]:
    donor = f"donor_{year}"
    total = f"total_donations_{year}"

    print(f"\n{year}")
    print("Non-donor but donations > 0:",
          ((df[donor] == 0) & (df[total] > 0)).sum())

    print("Donor but donations = 0:",
          ((df[donor] == 1) & (df[total] == 0)).sum())

2017
Non-donor but donations > 0: 0
Donor but donations = 0: 167

2019
Non-donor but donations > 0: 1
Donor but donations = 0: 173

In [15]:
df["giving_rate_2017"] = np.where(
    df["family_income_2017"] > 0,
    (df["total_donations_2017"] / df["family_income_2017"]) * 100,
    np.nan
)

df["giving_rate_2019"] = np.where(
    df["family_income_2019"] > 0,
    (df["total_donations_2019"] / df["family_income_2019"]) * 100,
    np.nan
)

In [16]:
df[
    [
        "family_income_2017",
        "total_donations_2017",
        "giving_rate_2017",
        "family_income_2019",
        "total_donations_2019",
        "giving_rate_2019"
    ]
].head(10)

,family_income_2017,total_donations_2017,giving_rate_2017,family_income_2019,total_donations_2019,giving_rate_2019
0,10800.0,0.0,0.000000,11028.0,300.0,2.720348
1,56000.0,0.0,0.000000,60970.0,0.0,0.000000
2,3705.0,0.0,0.000000,9380.0,0.0,0.000000
3,89347.0,0.0,0.000000,10000.0,0.0,0.000000
4,23500.0,0.0,0.000000,31000.0,0.0,0.000000
5,26000.0,0.0,0.000000,32726.0,0.0,0.000000
6,37207.0,0.0,0.000000,NaN,NaN,NaN
7,81139.0,0.0,0.000000,72200.0,0.0,0.000000
8,65000.0,100.0,0.153846,65100.0,250.0,0.384025
9,NaN,NaN,NaN,65000.0,0.0,0.000000

In [17]:
df.loc[
    (df["donor_2019"] == 0) &
    (df["total_donations_2019"] > 0),
    [
        "family_id_2019",
        "donor_status_2019",
        "total_donations_2019"
    ] + donation_cols_2019
]

,family_id_2019,donor_status_2019,total_donations_2019,religious_donations_2019,combo_donations_2019,needy_donations_2019,health_donations_2019,education_donations_2019,youth_donations_2019,cultural_donations_2019,community_donations_2019,environment_donations_2019,international_peace_donations_2019,other_donations_2019
7065,1069.0,5.0,2400.0,0.0,0.0,0.0,0.0,2400.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
df.loc[
    (df["donor_2017"] == 1) &
    (df["total_donations_2017"] == 0),
    "total_donations_2017"
] = np.nan

df.loc[
    (df["donor_2019"] == 1) &
    (df["total_donations_2019"] == 0),
    "total_donations_2019"
] = np.nan

In [19]:
df["giving_rate_2017"] = np.where(
    df["family_income_2017"] > 0,
    (df["total_donations_2017"] / df["family_income_2017"]) * 100,
    np.nan
)

df["giving_rate_2019"] = np.where(
    df["family_income_2019"] > 0,
    (df["total_donations_2019"] / df["family_income_2019"]) * 100,
    np.nan
)

In [20]:
print(
    "2017 donor but zero:",
    ((df["donor_2017"] == 1) & (df["total_donations_2017"] == 0)).sum()
)

print(
    "2019 donor but zero:",
    ((df["donor_2019"] == 1) & (df["total_donations_2019"] == 0)).sum()
)

2017 donor but zero: 0
2019 donor but zero: 0

In [21]:
row = df.loc[7065, donation_cols_2019]

row[row > 0]

education_donations_2019    2400.0
Name: 7065, dtype: float64

In [22]:
# Flag the contradictory 2019 record
df["donor_inconsistency_2019"] = (
    (df["donor_2019"] == 0) &
    (df["total_donations_2019"] > 0)
)

# Do not force this contradictory case into donor/non-donor analysis
df.loc[
    df["donor_inconsistency_2019"],
    "donor_2019"
] = np.nan

In [23]:
print("2019 contradictory donor records:",
      df["donor_inconsistency_2019"].sum())

2019 contradictory donor records: 1

In [24]:
import os

os.makedirs("../outputs", exist_ok=True)

df.to_csv(
    "../outputs/giving_happiness_clean.csv",
    index=False
)

In [25]:
os.path.exists("../outputs/giving_happiness_clean.csv")

True

In [26]:
df.shape

(10822, 53)